source ~/.vim/bundle.vimrc
source ~/.vim/basic.vimrc
source ~/.vim/window.vimrc
source ~/.vim/appearance.vimrc
source ~/.vim/keybind.vimrc
source ~/.vim/moving.vimrc
source ~/.vim/statusline.vimrc
source ~/.vim/filetype.vimrc
source ~/.vim/plugin_config.vimrc
