#!/bin/sh

# brew {{{
mkdir ~/brew && curl -L https://github.com/Homebrew/homebrew/tarball/master | tar xz --strip 1 -C ~/brew
rehash
./brew-bundle Brewfile
# }}}

# link dotfiles {{{
go run installer/install.go
# }}}

# defaults {{{
defaults write com.apple.dock autohide -bool true
defaults write com.apple.dock autohide-delay -float 0
defaults write com.apple.dock expose-animation-duration -float 0.1

defaults write com.apple.finder FXDefaultSearchScope -string 'SCcf'
defaults write com.apple.finder FXPreferredViewStyle -string "Nslv"

defaults write -g NSAutomaticSpellingCorrectionEnabled -bool false

defaults write -g NSQuitAlwaysKeepsWindows -bool false

defaults write -g NSDocumentSaveNewDocumentsToCloud -bool false

killall Finder
killall Dock
killall SystemUIServer
# }}}

# ruby & gems {{{
rbenv install 2.1.1
rbenv install 2.2.0
rbenv global 2.2.0

gem install foreman
gem install pry
gem install pry-doc
gem install ruby-anything
# }}}

# go cmds {{{
go get github.com/golang/lint/golint
go get golang.org/x/tools/cmd/vet
go get golang.org/x/tools/cmd/godoc
go get golang.org/x/tools/cmd/benchcmp
go get golang.org/x/tools/cmd/cover
go get golang.org/x/tools/cmd/gorename
go get github.com/mitchellh/gox
go get github.com/nsf/gocode
go get github.com/motemen/ghq
go get github.com/ToQoz/godecls
go get github.com/ToQoz/goimps
go get github.com/ToQoz/gomain
go get github.com/ToQoz/godeps
go get github.com/ToQoz/go-unitypackage
# }}}
