#!/bin/sh

xcode-select --install

# Install brew & brewed packages {{{
mkdir ~/brew && curl -L https://github.com/Homebrew/homebrew/tarball/master | tar xz --strip 1 -C ~/brew
export PATH=$HOME/brew/bin:$PATH
sh ./Brewbundle
export PATH=$HOME/.rbenv/shims:$PATH
export GOPATH=$HOME/_go
export GOROOT=$(go env GOROOT)
# }}}

# Configure karabiner/seil {{{
./osx/karabiner/config.sh
./osx/seil/config.sh
# }}}

# Set defaults {{{
defaults write com.apple.dock autohide -bool true
defaults write com.apple.dock autohide-delay -float 0
defaults write com.apple.dock expose-animation-duration -float 0.1

defaults write com.apple.finder FXDefaultSearchScope -string 'SCcf'
defaults write com.apple.finder FXPreferredViewStyle -string "Nslv"

defaults write -g NSAutomaticSpellingCorrectionEnabled -bool false
defaults write -g NSQuitAlwaysKeepsWindows -bool false
defaults write -g NSDocumentSaveNewDocumentsToCloud -bool false

killall Finder
killall Dock
killall SystemUIServer
# }}}

# Install dotfiles {{{
go run installer/install.go
# }}}

# Install ruby & gems(cmd) {{{
rbenv install 2.1.1
rbenv install 2.2.0
rbenv global 2.2.0

sh ./Gembundle

rbenv rehash
# }}}

# Install go packages(cmd) {{{
sh ./Gobundle
# }}}

# Fetch projects {{{
osascript -e 'tell application "Dropbox" to run'

# wait for sync ~/Dropbox/ghq-list.txt and ~/Dropbox/go-list.txt
while [ : ]
do
    ls ~/Dropbox/ghq-list.txt && ls ~/Dropbox/go-list.txt && break
    sleep 3
done

ghq import < ~/Dropbox/ghq-list.txt
# インストールしたいわけじゃなくて、リポジトリあつめてきたいだけなのでgo get -d
go get -d $(cat ~/Dropbox/go-list.txt)
# }}}

# vim:set ft=sh et foldmethod=marker:
