#!/bin/bash

casks=$(brew cask list)
cask() {
    case "$1" in
    install)
        if [ "$(echo "$casks" | grep -c "^$1$")" -gt 0 ]; then
            echo "[skip] brew cask $*" >> /dev/stderr
            return 0 # this is not error
        fi
        ;;
    esac
    brew cask "$@"
}

list=$(brew list)
install () {
    if [ "$(echo "$list" | grep -c "^$1$")" -gt 0 ]; then
        echo "[skip] brew install $*" >> /dev/stderr
        return 0 # this is not error
    fi

    HOMEBREW_NO_AUTO_UPDATE=1 brew install "$@"
}

taps=$(brew tap)
tap() {
    if [ "$(echo "$taps" | grep -c "^$1$")" -gt 0 ]; then
        echo "[skip] brew tap $*" >> /dev/stderr
        return 0 # this is not error
    fi

    brew tap "$@"
}

update() {
    brew update
}

tap caskroom/cask
tap homebrew/dupes
tap homebrew/versions
tap d12frosted/emacs-plus
tap caskroom/fonts
tap sanemat/font
tap toqoz/toqoz
tap toqoz/toqoz_cask

update

install pkg-config
install pcre
install openssl
install readline

# VCS {{{
install git
install git-lfs
install tig
install git-secrets
install mercurial
# }}}

# Zsh {{{
install zsh
install zsh-completions
# }}}

# Editor {{{
install vim --with-luajit
install macvim --with-luajit
install emacs-plus # d12frosted/emacs-plus
git clone --recursive https://github.com/syl20bnr/spacemacs ~/.emacs.d
osascript -e 'tell application "Finder" to make alias file to POSIX file "/usr/local/opt/emacs-plus/Emacs.app" at POSIX file "/Applications"'
# }}}

# Shims {{{
install homebrew/dupes/openssh
install md5sha1sum
install htop-osx
install pstree
install pidof
install wget
install make
install tree
install nkf
install expect
install homebrew/dupes/rsync
# }}}

# Benri {{{
install tmux
install reattach-to-user-namespace
install ghq
install peco
install the_silver_searcher
install jq
install xmlto
install lastpass-cli --with-pinentry --with-doc
install terraform
# }}}

# Chat {{{
install irssi
# }}}

# GUI/TUI {{{
install qt
if [ -n "$I_HAVE_TIME" ]; then
  install qcachegrind
  install gtk+
fi
install homebrew/dupes/ncurses
# }}}

# Ruby deps {{{
# (openssl and readline will be installed before reaching here)
install libyaml
install yajl
# }}}

# {{{ Nokogiri deps
install libxml2
install libxslt
install libiconv
# }}}

# Lauguage {{{
install go
install ruby-build
install rbenv
install python
install python3
install node
install yarn
cask install java
install scala
install swiftlint
install scalastyle
install swagger-codegen
install sourcekitten
install ShellCheck
install haskell-stack

if [ -n "$I_HAVE_TIME" ]; then
  install dmd
  install gauche
  install clozure-cl
  install leiningen
fi
# }}}

# Database {{{
install redis
brew services start redis
install mysql
brew services start mysql
# }}}

# GNU tools {{{
install coreutils
install gnu-sed
install gnu-tar
install gnu-getopt
install gawk
install findutils
install binutils
# }}}

# Font {{{
cask install font-source-code-pro
# }}}

# IME {{{
install toqoz/toqoz/uim
install toqoz/toqoz/uim-tmux
# }}}

# Documentation {{{
install asciidoc
install graphviz
# }}}

# Profiler/Benchmarker/Debugger {{{
install valgrind
# HTTP benchmarker
install wrk
# curses debugger
install cgdb
# }}}

# Network {{{
install dnsmasq
install ngrep
install nmap
# FIXME: sha256 missmatch
# install homebrew/binary/ngrok2
install mitmproxy
# install wireshark --with-qt is too slow
cask install wireshark
# }}}

# Media {{{
install imagemagick
install ffmpeg
# }}}

# iOS devtools {{{
install ios-webkit-debug-proxy
install xctool
install uncrustify
# }}}

# Ruby devtools {{{
# install refe
install rsense
# }}}

# Shell devtools {{{
install checkbashisms
# }}}

# Headless browsers {{{
install selenium-server-standalone
# }}}

# AWS {{{
install aws-elasticbeanstalk
install awscli
install dynamodb-local
# }}}

# Docker {{{
cask install docker
# }}}

# CLI for GUI app {{{
install chrome-cli
# Unarchiver
install unar
# }}}

# i18n {{{
install gettext
install intltool
# }}}

# for OSX specific situation {{{
cask install xquartz
cask install coconutbattery
cask install appcleaner
# }}}

# IME {{{
cask install toqoz/toqoz_cask/aquaskk
# }}}

# Browser {{{
cask install google-chrome
cask install firefox
# }}}

# Virtualisation {{{
cask install virtualbox
cask install vagrant
# }}}

# Key remap {{{
OSX_VERSION=$(sw_vers -productVersion | awk -F. '{printf "%2d%02d%02d", $1,$2,$3}')
if [ "$OSX_VERSION" -lt 101200 ]; then
  cask install karabiner
  cask install seil
else
  cask install toqoz/toqoz_cask/sands
fi
# }}}

# IDE/GUI manager {{{
cask install sourcetree
cask install mysqlworkbench
cask install sequel-pro
cask install visual-studio-code
if [ -n "$ANALYSIS" ]; then
  install r
  cask install rstudio
fi
if [ -n "$UNITY" ]; then
  cask install unity
  cask install mono-mdk
  cask install xamarin-studio
fi
if [ -n "$ANDROID" ]; then
  cask install android-studio
  cask install jd-gui
fi
# }}}

# Visual design {{{
if [ -n "$DESIGN" ]; then
  cask install couleurs
  cask install sketch
  cask install sketch-tool
  cask install texturepacker
  # X11 free version GMIP
  cask install lisanet-gimp
  cask install inkscape
  cask install firealpaca
  cask install blender
  cask install tiled
  cask install gyazo
fi
# }}}

# Fun {{{
if [ -n "$FUN" ]; then
  cask install soundcleod
  cask install radiant-player
  cask install vlc
  cask install cooviewer
  cask install steam
fi
# }}}

# WM {{{
cask install slate
# }}}

# Life {{{
cask install focus
cask install fantastical
# }}}

# Chat {{{
cask install slack
install slackcat
# }}}

# Auth {{{
if [ -n "$YUBIKEY" ]; then
  cask install yubikey-personalization-gui
  cask install yubikey-neo-manager
  cask install yubico-authenticator
fi
# }}}

tap OJFord/formulae
install loginitems
