#!/bin/sh

casks=$(brew cask list)
cask() {
    case "$1" in
    install)
        if [ $(echo "$casks" | grep "^$1$" | wc -l) -gt 0 ]; then
            echo "[skip] brew cask install $@" >> /dev/stderr
            return 0 # this is not error
        fi
        ;;
    esac
    brew cask $@
}

list=$(brew list)
install () {
    if [ $(echo "$list" | grep "^$1$" | wc -l) -gt 0 ]; then
        echo "[skip] brew install $@" >> /dev/stderr
        return 0 # this is not error
    fi

    brew install $@
}

taps=$(brew tap)
tap() {
    if [ $(echo "$taps" | grep "^$1$" | wc -l) -gt 0 ]; then
        echo "[skip] brew tap $@" >> /dev/stderr
        return 0 # this is not error
    fi

    brew tap $@
}

update() {
    brew update
}

source Brewfile
