#!/bin/sh

ghq list | xargs -I{} echo "https://{}" > ~/Dropbox/ghq-list.txt
echo "saved to ~/Dropbox/ghq-list.txt"

# あくまで、repositoryを記録したいだけなので、(sub packageとかいれたくない)ghqで記録する。
ghq list -p | grep "^$GOPATH/src/" | sed "s,^$GOPATH/src/,," > ~/Dropbox/go-list.txt
echo "saved to ~/Dropbox/go-list.txt"

echo "WARNING: export ios development certificates as .p12"
echo "  e.g."
echo "    iPhone Developer: .+"
echo "    iPhone Distribution: .+"
